### PR TITLE
Add the Adapter for GoFiber V2

### PR DESCRIPTION
**Pull request by realPy**
Implement the adapter and unit test for gofiber V2

### CODE REVIEW

**Comment by realPy** [comment]
The deepsource failed but the detected issue was not introduced by the new code 
root@059b5fefc2f7:/go/src/go-admin# go vet examples/fasthttp/main.go
# command-line-arguments
examples/fasthttp/main.go:71:26: call of eng.AddConfig copies lock value: github.com/GoAdminGroup/go-admin/modules/config.Config contains sync.RWMutex
root@059b5fefc2f7:/go/src/go-admin# go vet examples/gofiber/main.go
# command-line-arguments
examples/gofiber/main.go:76:26: call of eng.AddConfig copies lock value: github.com/GoAdminGroup/go-admin/modules/config.Config contains sync.RWMutex
root@059b5fefc2f7:/go/src/go-admin#

Same error on the other examples :/

**Comment by realPy** [comment]
@chenhg5 Can you help me with this?

Can't understand why i have this error but i check all example with go vet fasthttp , echo , all have the same error:
`examples/echo/main.go:70:26: call of eng.AddConfig copies lock value: github.com/GoAdminGroup/go-admin/modules/config.Config contains sync.RWMutex`

So why , the deepsource failed on this PR and not the other example on the master?

**Comment by chenhg5** [comment]
> @chenhg5 Can you help me with this?
> 
> Can't understand why i have this error but i check all example with go vet fasthttp , echo , all have the same error:
> `examples/echo/main.go:70:26: call of eng.AddConfig copies lock value: github.com/GoAdminGroup/go-admin/modules/config.Config contains sync.RWMutex`
> 
> So why , the deepsource failed on this PR and not the other example on the master?
> 
> I know you are busy but it will be great to support this PR. GoFiber is an amazon framework. I'll use go admin with gofiber and it work great 👍

@realPy Thanks for your PR and sorry for replying late, cause I am really busy recently. I will pull your code and look into the question.

**Comment by realPy** [comment]
@chenhg5 Thanks, I can wait :) i have forked the project until you have time to review.
I think i will make some other PR ;)

**Comment by realPy** [comment]
@chenhg5 Catch the lock mutex problem. The prototype of AddConfig in engine shoud be:
` func (eng *Engine) AddConfig(cfg *config.Config) *Engine`
because with `func (eng *Engine) AddConfig(cfg config.Config) *Engine` cfg is a copy of cfg and the mutex is "lock copy"

**Comment by realPy** [comment]
Hi @chenhg5 ,
Possibilities to integrate this pr? 
I'll use it since 4 month with no problem 👍

**Pull request merged**
